### ISSUE TITLE
Test "test_raw_value_ref" fails

### ISSUE THREAD

**Issue by Ch3ri0ur** [AdunSG/yaml-extender#5]
The difference is:
{'advanced_list': ['a b', 'c']} != {'advanced_list': ['a', 'b', 'c']}

The " ".join happens in:

https://github.com/AdunSG/yaml-extender/blob/7f9414847397e17d25770302371dd1c68032c149/src/yaml_extender/resolver/reference_resolver.py#L104C25-L104C25

```
    @patch("yaml_extender.yaml_loader.load")
    def test_raw_value_ref(loader_mock):
        # Test Lists
        content = yaml.safe_load(
            """
        my_list:
        - a
        - b
        advanced_list:
        - "{{ my_list }}"
        - c
        """
        )
        loader_mock.return_value = content
        file = XYmlFile(Path.cwd())
        expected = yaml.safe_load(
            """
        my_list:
        - a
        - b
        advanced_list:
        - a
        - b
        - c
        """
        )
>       assert file.content == expected
E       AssertionError: assert {'advanced_li...': ['a', 'b']} == {'advanced_li...': ['a', 'b']}
E         Omitting 1 identical items, use -vv to show
E         Differing items:
E         {'advanced_list': ['a b', 'c']} != {'advanced_list': ['a', 'b', 'c']}
E         Use -v to get more diff

tests/resolver_test/test_ref_resolver.py:371: AssertionError
```

**Comment by AdunSG** [comment]
Hi,
I fixed this issue and will provide a new version soon.

**Comment by Ch3ri0ur** [comment]
Maybe someone could set up some github actions to make sure that the tests actually pass.

I tried my hand with it, but coverage does not yet report correctly.
https://github.com/Ch3ri0ur/yaml-extender

Also the pull request is polluted by having ruff and ruff format run.

**Comment by AdunSG** [comment]
That is pretty nice!
can you create a PR so we can takeover the github actiosn config in this repo?

The issue should be fixed!
Please verify using verison 0.3.1

**Comment by Ch3ri0ur** [comment]
I will first have to deal with coverage/tox not working correctly. 

Do you need/want coverage? before I had a set of actions that did the matrix test with simple github actions.
The drawback there is, that you wont be able to run the matrix locally.

**Comment by AdunSG** [comment]
i'm  performing the tests 90% of the time through PyCharm anyway ^^

For a first step coverage would not be required, as this can also be added later.
